"""
Filesystem Watcher for AI Employee - Bronze Tier
Monitors the /Inbox folder and moves files to /Needs_Action with metadata
"""

import os
import time
import shutil
import logging
from pathlib import Path
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# Configuration
VAULT_PATH = Path(__file__).parent
INBOX_PATH = VAULT_PATH / "Inbox"
NEEDS_ACTION_PATH = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"

# Setup logging
LOGS_PATH.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOGS_PATH / "watcher.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class InboxHandler(FileSystemEventHandler):
    """Handles file creation events in the Inbox folder"""

    def __init__(self):
        self.processed_files = set()

    def on_created(self, event):
        """Called when a file or directory is created"""
        if event.is_directory:
            return

        file_path = Path(event.src_path)

        # Skip temporary files and already processed files
        if file_path.name.startswith('.') or file_path.name.startswith('~'):
            return

        if file_path.name in self.processed_files:
            return

        logger.info(f"New file detected: {file_path}")

        # Wait briefly to ensure file is fully written
        time.sleep(1)

        try:
            self.process_file(file_path)
        except Exception as e:
            logger.error(f"Error processing file {file_path}: {e}")

    def process_file(self, source_path: Path):
        """Process a file from Inbox and create metadata in Needs_Action"""

        timestamp = datetime.now().isoformat()
        filename = source_path.name
        base_name = source_path.stem

        # Create metadata markdown file in Needs_Action
        meta_content = f"""---
type: file_drop
source: Inbox
original_name: {filename}
size_bytes: {source_path.stat().st_size if source_path.exists() else 0}
detected_at: {timestamp}
status: pending
---

# File: {filename}

## File Details
- **Original Location**: {source_path}
- **Detected**: {timestamp}
- **Status**: Pending review

## Suggested Actions
- [ ] Review file contents
- [ ] Categorize and move to appropriate location
- [ ] Process if actionable
- [ ] Archive when complete

## Notes
<!-- Add processing notes here -->

---
*Auto-generated by Filesystem Watcher*
"""

        # Write metadata file
        meta_path = NEEDS_ACTION_PATH / f"FILE_{base_name}.md"
        meta_path.write_text(meta_content, encoding='utf-8')
        logger.info(f"Created metadata file: {meta_path}")

        # Move original file to Needs_Action
        dest_path = NEEDS_ACTION_PATH / filename
        shutil.move(str(source_path), str(dest_path))
        logger.info(f"Moved file to Needs_Action: {dest_path}")

        # Log the action
        self.log_action(filename, timestamp)

        # Mark as processed
        self.processed_files.add(filename)

    def log_action(self, filename: str, timestamp: str):
        """Log the file processing action"""
        log_entry = f"{timestamp} - PROCESSED - {filename}\n"
        log_file = LOGS_PATH / "inbox_activity.log"
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(log_entry)


def main():
    """Main entry point for the watcher"""

    # Ensure directories exist
    INBOX_PATH.mkdir(exist_ok=True)
    NEEDS_ACTION_PATH.mkdir(exist_ok=True)

    logger.info("=" * 50)
    logger.info("AI Employee - Filesystem Watcher Started")
    logger.info(f"Watching: {INBOX_PATH}")
    logger.info(f"Output: {NEEDS_ACTION_PATH}")
    logger.info("=" * 50)

    # Create event handler and observer
    event_handler = InboxHandler()
    observer = Observer()
    observer.schedule(event_handler, str(INBOX_PATH), recursive=False)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info("Stopping watcher...")
        observer.stop()
    observer.join()


if __name__ == "__main__":
    main()
