"""
Process Inbox - Agent Skill Script
Processes files from Needs_Action and moves them to Done
"""

import os
import shutil
import logging
from pathlib import Path
from datetime import datetime

# Paths
VAULT_PATH = Path(__file__).parent
NEEDS_ACTION_PATH = VAULT_PATH / "Needs_Action"
DONE_PATH = VAULT_PATH / "Done"
LOGS_PATH = VAULT_PATH / "Logs"
DASHBOARD_PATH = VAULT_PATH / "Dashboard.md"

# Setup logging
LOGS_PATH.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def get_pending_items():
    """Get all pending markdown files from Needs_Action"""
    if not NEEDS_ACTION_PATH.exists():
        return []

    items = []
    for file_path in NEEDS_ACTION_PATH.glob("*.md"):
        content = file_path.read_text(encoding='utf-8')
        if "status: pending" in content or "status:pending" in content:
            items.append(file_path)

    return items


def process_item(item_path: Path):
    """Process a single item and mark as complete"""

    logger.info(f"Processing: {item_path.name}")

    # Read the file
    content = item_path.read_text(encoding='utf-8')

    # Mark as complete in the content
    timestamp = datetime.now().isoformat()
    updated_content = content.replace(
        "status: pending",
        f"status: completed\ncompleted_at: {timestamp}"
    )

    # Write updated content
    item_path.write_text(updated_content, encoding='utf-8')

    # Move to Done
    dest_path = DONE_PATH / item_path.name
    shutil.move(str(item_path), str(dest_path))

    logger.info(f"Completed and moved to Done: {item_path.name}")
    return True


def update_dashboard(processed_count: int):
    """Update the Dashboard with current stats"""

    if not DASHBOARD_PATH.exists():
        logger.warning("Dashboard.md not found")
        return

    # Count current items
    needs_action_count = len(list(NEEDS_ACTION_PATH.glob("*.md"))) if NEEDS_ACTION_PATH.exists() else 0
    done_count = len(list(DONE_PATH.glob("*.md"))) if DONE_PATH.exists() else 0

    # Update dashboard content
    dashboard_content = f"""# AI Employee Dashboard

*Last updated: {datetime.now().isoformat()}*

## Quick Stats

| Metric | Value |
|--------|-------|
| Pending Actions | {needs_action_count} |
| Completed Today | {done_count} |
| System Status | Active |

## Active Items

### Needs Action ({needs_action_count})
"""

    # Add list of pending items
    if needs_action_count > 0:
        for item in NEEDS_ACTION_PATH.glob("*.md"):
            dashboard_content += f"- {item.name}\n"
    else:
        dashboard_content += "- No pending items\n"

    dashboard_content += f"""
### Recently Completed ({min(5, done_count)} shown)
"""

    # Add recently completed
    if done_count > 0:
        done_items = sorted(DONE_PATH.glob("*.md"), key=lambda x: x.stat().st_mtime, reverse=True)[:5]
        for item in done_items:
            dashboard_content += f"- {item.name}\n"
    else:
        dashboard_content += "- No completed items yet\n"

    dashboard_content += f"""
## Quick Links

- [Company Handbook](./Company_Handbook.md)
- [Needs Action Folder](./Needs_Action/)
- [Done Folder](./Done/)

## Manual Commands

To process pending items:
```bash
python process_inbox.py
```

---
*Generated by AI Employee v0.1 - Bronze Tier*
*Last processed: {processed_count} items*
"""

    DASHBOARD_PATH.write_text(dashboard_content, encoding='utf-8')
    logger.info("Dashboard updated")


def main():
    """Main entry point"""

    # Ensure directories exist
    DONE_PATH.mkdir(exist_ok=True)

    logger.info("=" * 50)
    logger.info("Process Inbox - Starting")
    logger.info("=" * 50)

    # Get pending items
    pending_items = get_pending_items()

    if not pending_items:
        logger.info("No pending items found in Needs_Action")
        update_dashboard(0)
        return

    logger.info(f"Found {len(pending_items)} pending item(s)")

    # Process each item
    processed_count = 0
    for item in pending_items:
        try:
            if process_item(item):
                processed_count += 1
        except Exception as e:
            logger.error(f"Error processing {item.name}: {e}")

    # Update dashboard
    update_dashboard(processed_count)

    logger.info("=" * 50)
    logger.info(f"Completed: {processed_count}/{len(pending_items)} items processed")
    logger.info("=" * 50)


if __name__ == "__main__":
    main()
